import Image from "next/image";
import { CheckCircle2, PackageCheck, Route, Truck, WashingMachine } from "lucide-react";
import { CommercialInquiryForm } from "@/components/commercial-inquiry-form";
import { PageShell, SectionHeading } from "@/components/page-shell";
import { commercialIndustries, commercialItems } from "@/lib/site-data";

const benefits = ["Service available 7 days a week", "No long-term contract", "No cancellation fee", "Greater Toronto Area coverage"] as const;

export default function CommercialPage() {
  return (
    <PageShell title="Commercial laundry that works around your business." description="Flexible pickup, professional cleaning and reliable delivery for businesses across the Greater Toronto Area." eyebrow="COMMERCIAL LAUNDRY" image="/images/commercial-laundry-gta.jpg" imageAlt="A professional commercial laundry facility processing white linens">
      <section className="bg-vite-navy px-5 text-vite-paper sm:px-8 lg:px-[72px]"><div className="mx-auto grid max-w-[1296px] grid-cols-2 gap-px bg-vite-paper/15 md:grid-cols-4">{benefits.map((benefit) => <p key={benefit} className="bg-vite-navy px-5 py-6 text-sm font-medium leading-5 lg:px-8">{benefit}</p>)}</div></section>

      <section className="bg-vite-paper px-5 py-20 sm:px-8 lg:px-[72px] lg:py-24"><div className="mx-auto max-w-[1296px]"><SectionHeading title="From dirty laundry to finished return." description="Vite helps businesses outsource recurring laundry operations with pickup, professional cleaning, finishing and delivery." /><div className="mt-12 grid gap-8 sm:grid-cols-2 lg:grid-cols-4">{[
        { title: "Business pickup", body: "Choose a recurring schedule that fits your operation.", icon: Truck },
        { title: "Professional cleaning", body: "Wash, dry and specialty care are matched to the item.", icon: WashingMachine },
        { title: "Fold and finish", body: "Items are folded, pressed or packaged to approved requirements.", icon: PackageCheck },
        { title: "Delivery back", body: "Finished laundry returns to the right business location.", icon: Route },
      ].map((item) => { const Icon = item.icon; return <article key={item.title} className="border-l border-vite-line pl-6"><Icon aria-hidden="true" className="size-7 text-vite-cobalt" strokeWidth={1.7} /><h2 className="mt-6 font-display text-2xl text-vite-navy">{item.title}</h2><p className="mt-3 text-sm leading-6 text-vite-muted">{item.body}</p></article>; })}</div></div></section>

      <section className="bg-vite-surface px-5 py-20 sm:px-8 lg:px-[72px] lg:py-24"><div className="mx-auto max-w-[1296px]"><SectionHeading title="Everyday commercial laundry, handled professionally." description="Specialty, oversized and heavily soiled items require confirmation before service." /><div className="mt-12 grid grid-cols-2 gap-3 sm:grid-cols-4">{commercialItems.map((item) => { const Icon = item.icon; return <div key={item.label} className="rounded-[18px] border border-vite-line bg-vite-paper p-5"><Icon aria-hidden="true" className="size-5 text-vite-cobalt" strokeWidth={1.7} /><p className="mt-5 font-display text-lg text-vite-navy">{item.label}</p></div>; })}</div></div></section>

      <section className="bg-vite-paper px-5 py-20 sm:px-8 lg:px-[72px] lg:py-24"><div className="mx-auto max-w-[1296px]"><SectionHeading title="Service plans for the way your industry operates." description="Pickup frequency, item mix and finishing requirements can be tailored to each business account." /><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{commercialIndustries.map((industry) => { const Icon = industry.icon; return <article key={industry.title} className="rounded-[24px] bg-vite-blue-soft p-7"><Icon aria-hidden="true" className="size-6 text-vite-cobalt" strokeWidth={1.7} /><h2 className="mt-6 font-display text-2xl text-vite-navy">{industry.title}</h2><p className="mt-3 text-sm leading-6 text-vite-muted">{industry.description}</p></article>; })}</div></div></section>

      <section className="bg-vite-blue-soft px-5 py-20 sm:px-8 lg:px-[72px] lg:py-24"><div className="mx-auto grid max-w-[1296px] items-center gap-12 lg:grid-cols-[0.95fr_1.05fr] lg:gap-20"><div><SectionHeading title="Your standards, built into every service." description="Approved account requirements can be recorded for recurring pickups and multiple business locations." /><ul className="mt-8 grid gap-4">{["Custom detergent requirements", "Water temperature preferences", "Folding and finishing standards", "Packaging instructions", "Multiple-location schedules", "Complimentary commercial laundry bags"].map((item) => <li key={item} className="flex items-center gap-3 text-sm text-vite-ink"><CheckCircle2 aria-hidden="true" className="size-5 text-vite-cobalt" strokeWidth={1.7} />{item}</li>)}</ul></div><div className="relative min-h-[460px] overflow-hidden rounded-[28px]"><Image src="/images/audience-businesses.jpg" alt="A Vite team member supporting a local business" fill sizes="(min-width: 1024px) 55vw, 100vw" className="object-cover" /></div></div></section>

      <section className="bg-vite-navy px-5 py-20 text-vite-paper sm:px-8 lg:px-[72px] lg:py-24"><div className="mx-auto grid max-w-[1296px] gap-12 lg:grid-cols-[1fr_1.1fr] lg:gap-20"><div><h2 className="font-display text-4xl leading-[1.03] sm:text-5xl">Flexible pricing based on what you use.</h2><p className="mt-5 max-w-xl text-base leading-7 text-vite-blue-soft/80">Commercial pricing is tailored to laundry type, volume, pickup frequency, location and handling requirements. Recurring customers may qualify for preferred commercial rates.</p><div className="mt-8 rounded-[20px] bg-vite-cobalt p-6 text-sm leading-7"><p>Laundry type + volume + frequency + location + handling requirements = custom quote</p></div></div><div className="rounded-[28px] bg-vite-paper p-7 text-vite-ink sm:p-9"><h2 className="font-display text-3xl text-vite-navy">Request a Commercial Quote</h2><p className="mt-3 text-sm leading-6 text-vite-muted">Tell us what you wash, how much, how often and where your business operates.</p><div className="mt-8"><CommercialInquiryForm /></div></div></div></section>
    </PageShell>
  );
}
